### PR TITLE
Add expiration date support through level-ttl

### LINKED ISSUE #40: Expiration date
We should allow users to make a score expire once it is. Having the infrastructure in place to do this will also allow #25, since the Dropbox Savers API requires a URL to be present for the file to be stored.

### PR DESCRIPTION
**Pull request by TimothyGu**
Fixes #40. A step towards #25.

The menu is hidden on mobile for now as I am yet to decide how (or if) to lay it out.

### CODE REVIEW

**Comment by TimothyGu** [comment]
Ping.

**Comment by scottlinux** [comment]
Just leave hidden for mobile?

**Comment by trevordixon** [comment]
Pardon my ignorance, but I don't understand why this is necessary for the Dropbox saver. How's how I image the Dropbox save thing ought to work:

1. The user hits save.
2. Upload a temporary .ly file to S3.
3. Call `Dropbox.save(...)`.
4. Dropbox fetches the score.
5. Five minutes later, the file on S3 is deleted.

Am I misunderstanding the Dropbox save flow? I'm not sure this feature is worth the extra, though slight, code complexity or UI clutter if it isn't necessary to make Dropbox work.

**Comment by TimothyGu** [comment]
First, I need to make it clear that neither your flow nor mine is the status quo (it's not crystal clear to me if you already know this or not :). The .ly is not uploaded to S3 but rather directly passed to the Lambda function (through a POST request basically).

What I'm proposing is do NOT store the .ly on S3 but rather locally and temporarily, so that it is available for a short time through the `/raw/:id/:rev` API.

Either way is fine for me. This PR adds some more features *while* making Dropbox possible, while S3 makes the server less dependent on LevelDB et al, and easier to migrate to other architectures. It's your call.

**Pull request closed without merging**
